"""Import local IME dictionaries as a private Rime dictionary pack.

The export is never copied into the repository.  Rime uses full pinyin codes
for both the full-pinyin and Xiaohe schemas; double-pinyin codes must not be
written into the dictionary source.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from pypinyin import Style, lazy_pinyin, pinyin

from . import dictionary_formats, paths, rime_settings, yaml_io

PACK_NAME = "language_input_sogou"
_MARKER = "# Generated by Language Input from a local text export."
_MAX_BYTES = 64 * 1024 * 1024
_HAN = re.compile(r"^[\u3400-\u9fff\U00020000-\U0002fa1f]{1,32}$")
_SYLLABLE = re.compile(r"^[a-zv]+$")


class DictionaryImportError(ValueError):
    """The source cannot be imported without guessing its format."""


@dataclass(frozen=True)
class Entry:
    word: str
    code: str
    weight: int


@dataclass(frozen=True)
class Preview:
    source: str
    encoding: str
    entries: int
    skipped: int
    generated_readings: int
    files: int = 1
    ignored_files: int = 0


@dataclass(frozen=True)
class LocalSource:
    label: str
    path: str
    detail: str


def discover_local_sources(profile: str | os.PathLike[str] | None = None) -> list[LocalSource]:
    """Offer only recognized, locally present formats; never read unknown caches."""
    home = Path(profile) if profile is not None else Path.home()
    found: list[LocalSource] = []
    sogou = home / "AppData" / "LocalLow" / "SogouPY"
    personal = sogou / "sgim_gd_usr.bin"
    if _has_header(personal, b"SGPU"):
        found.append(LocalSource("搜狗输入法 · 本机个人词库", str(personal), "自动读取本机 SGPU 用户词库"))
    cells = sogou / "scd"
    if cells.is_dir():
        supported = sum(
            1 for path in cells.glob("*.scel")
            if _supported_scel_header(path)
        )
        if supported:
            found.append(LocalSource("搜狗输入法 · 已安装细胞词库", str(cells), f"发现 {supported} 个普通 .scel 文件"))
    microsoft = home / "AppData" / "Roaming" / "Microsoft" / "InputMethod" / "Chs" / "ChsPinyinUDL.dat"
    if _has_header(microsoft, b"\x55\xaa\x88\x81"):
        found.append(LocalSource("微软拼音 · 本机用户词库", str(microsoft), "自动读取 ChsPinyinUDL.dat"))
    return found


def _has_header(path: Path, signature: bytes) -> bool:
    try:
        with path.open("rb") as handle:
            return handle.read(len(signature)) == signature
    except OSError:
        return False


def _supported_scel_header(path: Path) -> bool:
    try:
        with path.open("rb") as handle:
            data = handle.read(8)
        return len(data) == 8 and 0x1540 <= int.from_bytes(data[:4], "little") <= path.stat().st_size
    except OSError:
        return False


def _decode(raw: bytes) -> tuple[str, str]:
    if raw.startswith(b"\xef\xbb\xbf"):
        return raw.decode("utf-8-sig"), "UTF-8"
    if raw.startswith((b"\xff\xfe", b"\xfe\xff")):
        return raw.decode("utf-16"), "UTF-16"
    if b"\x00" in raw[:1024]:
        try:
            return raw.decode("utf-16-le"), "UTF-16 LE"
        except UnicodeError:
            pass
    for encoding in ("utf-8", "gb18030"):
        try:
            return raw.decode(encoding), encoding.upper()
        except UnicodeError:
            continue
    raise DictionaryImportError("无法识别文本编码；请从搜狗导出 TXT 文本词库。")


def _split_line(line: str) -> list[str]:
    if "\t" in line:
        return [part.strip() for part in line.split("\t")]
    if "," in line:
        return [part.strip().strip('"') for part in line.split(",")]
    return line.strip().split(maxsplit=1)


def _code(word: str, fields: list[str]) -> tuple[str | None, bool]:
    """Preserve explicit separated pinyin; derive it for word-only exports."""
    readings = pinyin(word, style=Style.NORMAL, heteronym=True, errors="default")
    for field in fields:
        candidate = field.lower().replace("ü", "v").replace("u:", "v")
        syllables = re.split(r"[\s']+", candidate.strip())
        if len(syllables) == len(word) and all(
            _SYLLABLE.fullmatch(s) and s in variants
            for s, variants in zip(syllables, readings)
        ):
            return " ".join(syllables), False
    syllables = lazy_pinyin(word, style=Style.NORMAL, errors="default")
    if len(syllables) != len(word) or not all(_SYLLABLE.fullmatch(s) for s in syllables):
        return None, True
    return " ".join(syllables), True


def _read_export(source: str | os.PathLike[str]) -> tuple[Preview, dict[tuple[str, str], Entry]]:
    path = Path(source)
    if path.is_dir():
        all_files = sorted(path.glob("*.scel"))
        files = [candidate for candidate in all_files if _supported_scel_header(candidate)]
        ignored = len(all_files) - len(files)
        if not files:
            raise DictionaryImportError("目录中没有可读取的普通 .scel 细胞词库。")
    elif path.is_file():
        files, ignored = [path], 0
    else:
        raise DictionaryImportError("请选择存在的词库文件，或从列表选择已检测到的本机输入法。")
    if sum(item.stat().st_size for item in files) > _MAX_BYTES:
        raise DictionaryImportError("所选词库超过 64 MB，请分批导入。")
    all_entries: dict[tuple[str, str], Entry] = {}
    skipped = generated = 0
    formats: list[str] = []
    for item in files:
        if item.suffix.lower() in {".scel", ".qcel", ".bin", ".dat"}:
            try:
                encoding, rows = dictionary_formats.read_binary(item)
            except (OSError, dictionary_formats.FormatError) as exc:
                if path.is_dir():
                    ignored += 1
                    continue
                raise DictionaryImportError(f"{item.name}：{exc}") from exc
            entries = {}
            for word, syllables, frequency in rows:
                if not _HAN.fullmatch(word) or len(syllables) != len(word) or not all(
                    _SYLLABLE.fullmatch(s) for s in syllables
                ):
                    skipped += 1
                    continue
                code = " ".join(syllables)
                weight = 1000 + min(max(frequency, 0), 9000)
                key = (word, code)
                old = entries.get(key)
                if old is None or old.weight < weight:
                    entries[key] = Entry(word, code, weight)
        else:
            entries, encoding, text_skipped, text_generated = _read_text(item)
            skipped += text_skipped
            generated += text_generated
        formats.append(encoding)
        for key, entry in entries.items():
            old = all_entries.get(key)
            if old is None or old.weight < entry.weight:
                all_entries[key] = entry
    if not all_entries:
        raise DictionaryImportError("没有识别到可导入的汉字词条。")
    format_label = formats[0] if len(set(formats)) == 1 else "、".join(sorted(set(formats)))
    return Preview(str(path), format_label, len(all_entries), skipped, generated, len(formats), ignored), all_entries


def _read_text(path: Path) -> tuple[dict[tuple[str, str], Entry], str, int, int]:
    text, encoding = _decode(path.read_bytes())
    if any(ord(char) < 32 and char not in "\r\n\t" for char in text):
        raise DictionaryImportError("文件包含二进制内容；请选择搜狗导出的 TXT 文本词库。")
    entries: dict[tuple[str, str], Entry] = {}
    skipped = generated = 0
    for raw_line in text.splitlines():
        line = raw_line.strip().lstrip("\ufeff")
        if not line or line.startswith("#"):
            continue
        fields = _split_line(line)
        word = fields[0].strip('"') if fields else ""
        if word in {"词语", "词条", "单词"} and any(
            field in {"拼音", "读音", "词频", "频率"} for field in fields[1:]
        ):
            continue
        if not _HAN.fullmatch(word):
            skipped += 1
            continue
        code, was_generated = _code(word, fields[1:])
        if code is None:
            skipped += 1
            continue
        generated += int(was_generated)
        frequency = next((int(f) for f in fields[1:] if f.isdecimal()), 0)
        weight = 1000 + min(frequency, 9000)
        key = (word, code)
        old = entries.get(key)
        if old is None or old.weight < weight:
            entries[key] = Entry(word, code, weight)
    return entries, encoding, skipped, generated


def preview_export(source: str | os.PathLike[str]) -> Preview:
    """Inspect locally without displaying or transmitting personal words."""
    preview, _ = _read_export(source)
    return preview


def _pack_path(user_dir: Path) -> Path:
    return user_dir / f"{PACK_NAME}.dict.yaml"


def _read_existing_pack(path: Path) -> dict[tuple[str, str], Entry]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8-sig")
    if not text.startswith(_MARKER + "\n") or f"name: {PACK_NAME}\n" not in text:
        raise DictionaryImportError(f"已有同名词库不是本应用生成，未覆盖：{path}")
    if "\n...\n" not in text:
        raise DictionaryImportError(f"现有导入词库格式不完整：{path}")
    rows = text.split("\n...\n", 1)[1]
    entries: dict[tuple[str, str], Entry] = {}
    for row in rows.splitlines():
        if not row.strip():
            continue
        fields = row.split("\t")
        if len(fields) != 3 or not fields[2].isdecimal():
            raise DictionaryImportError(f"现有导入词库含无法识别的行：{path}")
        entry = Entry(fields[0], fields[1], int(fields[2]))
        entries[(entry.word, entry.code)] = entry
    return entries


def _render_pack(entries: dict[tuple[str, str], Entry]) -> str:
    version = datetime.now(timezone.utc).strftime("%Y.%m.%d.%H%M%S")
    lines = [
        _MARKER,
        "# UTF-8; private to this Rime user directory.",
        "---",
        f"name: {PACK_NAME}",
        f'version: "{version}"',
        "sort: by_weight",
        "use_preset_vocabulary: false",
        "...",
    ]
    lines.extend(
        f"{entry.word}\t{entry.code}\t{entry.weight}"
        for entry in sorted(entries.values(), key=lambda e: (e.word, e.code))
    )
    return "\n".join(lines) + "\n"


def _patch_document(path: Path):
    document = rime_settings._load_rt(path) if path.is_file() else rime_settings._require_map()()
    patch = document.get("patch")
    if patch is None:
        patch = rime_settings._require_map()()
        document["patch"] = patch
    if not isinstance(patch, dict):
        raise DictionaryImportError(f"方案补丁格式不正确：{path}")
    return document, patch


def _ensure_pack(path: Path, *, write: bool = True) -> bool:
    document, patch = _patch_document(path)
    for key in ("translator/packs", "translator/packs/+"):
        found = rime_settings._find_leaf(patch, key.split("/"))
        if found:
            parent, leaf = found
            value = parent[leaf]
            if not isinstance(value, list):
                raise DictionaryImportError(f"方案词库配置不是列表：{path}")
            if PACK_NAME in value:
                return False
            value.append(PACK_NAME)
            break
    else:
        patch["translator/packs/+"] = [PACK_NAME]
    if write:
        yaml_io.backup_file(path)
        rime_settings._dump_rt(path, document)
    return True


def import_export(
    source: str | os.PathLike[str],
    *,
    user_dir: str | os.PathLike[str] | None = None,
    deploy: bool = True,
) -> dict:
    """Merge a recognized source into the private pack and activate both schemas."""
    preview, incoming = _read_export(source)
    target_dir = Path(user_dir) if user_dir is not None else paths.rime_user_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    pack_path = _pack_path(target_dir)
    existing = _read_existing_pack(pack_path)
    merged = dict(existing)
    for key, entry in incoming.items():
        old = merged.get(key)
        if old is None or old.weight < entry.weight:
            merged[key] = entry

    # Validate pack-list shapes before changing any user-owned file.
    for schema_id in rime_settings.LANGUAGE_SCHEMAS:
        _ensure_pack(target_dir / f"{schema_id}.custom.yaml", write=False)
    if merged != existing:
        yaml_io.backup_file(pack_path)
        yaml_io.atomic_write_text(pack_path, _render_pack(merged))
    for schema_id in rime_settings.LANGUAGE_SCHEMAS:
        _ensure_pack(target_dir / f"{schema_id}.custom.yaml")

    result = {
        "preview": preview,
        "total": len(merged),
        "added": len(set(merged) - set(existing)),
        "pack_path": str(pack_path),
        "deploy": None,
        "clean": None,
    }
    if deploy:
        deployed = rime_settings.run_deploy()
        compiled = all(
            PACK_NAME in (
                (rime_settings._load_yaml(target_dir / "build" / f"{schema_id}.schema.yaml") or {})
                .get("translator", {})
                .get("packs", [])
            )
            for schema_id in rime_settings.LANGUAGE_SCHEMAS
        )
        compiled = compiled and (target_dir / "build" / f"{PACK_NAME}.table.bin").is_file()
        result["deploy"] = deployed
        result["clean"] = bool(deployed["clean"] and compiled)
    return result
