"""Rime / Weasel settings operations: appearance, switches and memory.

This module implements the three pages that used to be placeholders:

* **Appearance** -- the candidate-window style.  Values are read from the
  *installed* ``<weasel_root>\\data\\weasel.yaml`` (the real key set is
  enumerated, never guessed) and written to the app-owned
  ``<userdir>\\weasel.custom.yaml`` under a **merged** ``patch:`` mapping, so
  the file's existing keys (e.g. ``style/color_scheme``) are preserved.
* **Switches** -- the Language Input F4 switches.  Persisted in
  ``<userdir>\\user.yaml`` as ``var/option/<name>`` (design doc §5.5).  The
  three ``language_input_en/ja/es`` options form a mutually exclusive radio
  group.  ``hotkeys()`` exposes the configured bindings read-only.
* **Memory / dictionary** -- ``translator/enable_user_dict`` patched through
  each schema's ``<schema>.custom.yaml`` (design doc §8), user-dictionary
  presence/size, ``/sync`` and the detached ``/dict`` launcher.

Writing rules (design doc §5.6): UTF-8 **without BOM**, LF newlines, atomic
(temp + ``os.replace``), back up first.  Rime's own exported configuration is
never round-trip-rewritten; the app-owned patch files ``weasel.custom.yaml``
and ``<schema>.custom.yaml`` are edited with a round-trip ruamel document
(like :mod:`schema_patch`), so nested and flat ``patch:`` spellings are both
resolved for reads and writes.  ``user.yaml`` is edited surgically (line-based)
via :mod:`yaml_io`.

Live config writes (``user.yaml``) go through
:func:`server.server_stopped`: the server holds ``user.yaml`` with
``auto_save`` and rewrites the whole file, so every switch edit is a
stop → wait → atomic-write → restart transaction (design §5.6 / B2).

``/deploy`` returns exit code ``0`` even for invalid YAML: success is judged by
an empty stderr **and** by re-reading the resulting state.
"""

from __future__ import annotations

import os
import re
import subprocess
import threading
from io import StringIO
from pathlib import Path
from typing import Any

from . import deploy as _deploy
from . import paths, server as _server, winproc, yaml_io

try:  # ruamel is a declared dependency, but keep import failures graceful.
    from ruamel.yaml import YAML as _YAML
    from ruamel.yaml.comments import CommentedMap as _CommentedMap

    HAS_RUAMEL = True
except Exception:  # pragma: no cover - dependency missing
    _YAML = None  # type: ignore
    _CommentedMap = None  # type: ignore
    HAS_RUAMEL = False

__all__ = [
    "RimeSettingsError",
    "LANGUAGE_SCHEMAS",
    "LANGUAGE_GROUP",
    "SWITCH_ORDER",
    "SWITCH_LABELS",
    "REQUESTED_STYLE_KEYS",
    "MANAGED_STYLE_KEYS",
    "read_weasel_style",
    "available_color_schemes",
    "current_style",
    "apply_style",
    "run_deploy",
    "language_input_switches",
    "read_switches",
    "set_switch",
    "set_switches",
    "hotkeys",
    "learning_state",
    "set_learning",
    "sync_user_data",
    "dict_manager_note",
    "open_dict_manager",
]


class RimeSettingsError(RuntimeError):
    """A settings operation could not be completed safely."""


# --- constants --------------------------------------------------------------

LANGUAGE_SCHEMAS: tuple[str, ...] = (
    "language_input_flypy",
    "language_input_pinyin",
)

LANGUAGE_GROUP: tuple[str, ...] = (
    "language_input_en",
    "language_input_ja",
    "language_input_es",
)

SWITCH_ORDER: tuple[str, ...] = (
    "language_input_gloss",
    "language_input_ai",
    "language_input_model_m2m100",
    "language_input_en",
    "language_input_ja",
    "language_input_es",
    "language_input_speech",
)

SWITCH_LABELS: dict[str, str] = {
    "language_input_gloss": "总注释开关",
    "language_input_ai": "AI 翻译",
    "language_input_model_m2m100": "慢速实验模型（M2M100，冷请求超 1 秒）",
    "language_input_en": "目标语言：英语",
    "language_input_ja": "目标语言：日语",
    "language_input_es": "目标语言：西班牙语",
    "language_input_speech": "朗读",
}

# Requested style concepts -> the key that actually exists in weasel.yaml.
# ``style/corner_radius`` is the name used by the design doc; the installed
# file nests it as ``style/layout/corner_radius``.
REQUESTED_STYLE_KEYS: dict[str, str] = {
    "style/color_scheme": "style/color_scheme",
    "style/font_point": "style/font_point",
    "style/corner_radius": "style/layout/corner_radius",
    "style/horizontal": "style/horizontal",
    "style/inline_preedit": "style/inline_preedit",
    "style/label_format": "style/label_format",
    "style/comment_font_point": "style/comment_font_point",
}

#: The ``weasel.custom.yaml`` style keys the 外观 page writes.  ``恢复默认``
#: removes exactly these (a ``None`` value in :func:`apply_style`), so the
#: installed defaults apply again without touching unrelated patch keys.
MANAGED_STYLE_KEYS: tuple[str, ...] = (
    "style/color_scheme",
    "style/font_point",
    "style/horizontal",
    "style/inline_preedit",
)

_HEADER_COMMENT = (
    "Generated by Language Input settings: learning / user-dictionary option.\n"
)

_MISSING = object()

# Serialises our own deployer invocations (the deployer has its own Windows
# mutex; this only prevents *this* process from launching two at once).
_DEPLOYER_LOCK = threading.Lock()


# --- path / yaml helpers ----------------------------------------------------

def _coerce_user_dir(user_dir: str | os.PathLike[str] | None) -> Path:
    return Path(user_dir) if user_dir is not None else paths.rime_user_dir()


def _weasel_root(root: str | os.PathLike[str] | None) -> Path | None:
    if root is not None:
        return Path(root)
    return paths.weasel_root()


def _weasel_yaml_path(root: str | os.PathLike[str] | None = None) -> Path | None:
    resolved = _weasel_root(root)
    if resolved is None:
        return None
    return Path(resolved) / "data" / "weasel.yaml"


def _user_yaml_path(user_dir: str | os.PathLike[str] | None = None) -> Path:
    return _coerce_user_dir(user_dir) / "user.yaml"


def _custom_weasel_path(user_dir: str | os.PathLike[str] | None = None) -> Path:
    return _coerce_user_dir(user_dir) / "weasel.custom.yaml"


def _compiled_schema_path(
    schema_id: str, user_dir: str | os.PathLike[str] | None = None
) -> Path:
    return _coerce_user_dir(user_dir) / "build" / f"{schema_id}.schema.yaml"


def _custom_schema_path(
    schema_id: str, user_dir: str | os.PathLike[str] | None = None
) -> Path:
    return _coerce_user_dir(user_dir) / f"{schema_id}.custom.yaml"


def _userdb_path(user_dir: str | os.PathLike[str] | None = None) -> Path:
    return _coerce_user_dir(user_dir) / "luna_pinyin.userdb"


def _require_yaml():
    if _YAML is None:  # pragma: no cover - dependency missing
        raise RimeSettingsError("ruamel.yaml is required for Rime settings")
    return _YAML


def _require_map():
    if _CommentedMap is None:  # pragma: no cover - dependency missing
        raise RimeSettingsError("ruamel.yaml is required for Rime settings")
    return _CommentedMap


def _load_yaml(path: Path | None) -> Any:
    """Parse a Rime config file read-only (never used to rewrite it)."""
    if path is None or not Path(path).is_file():
        return None
    yaml = _require_yaml()
    try:
        text = Path(path).read_text(encoding="utf-8-sig")
        # Rime tolerates tabs (e.g. ``max_width: 0\t#comment`` in weasel.yaml)
        # but strict YAML does not; tabs are only ever whitespace here.
        text = text.replace("\t", " ")
        return yaml(typ="safe").load(text)
    except RimeSettingsError:
        raise
    except Exception as exc:  # noqa: BLE001 - malformed input
        raise RimeSettingsError(f"cannot parse {path}: {exc}") from exc


def _flatten(mapping: Any, prefix: str = "") -> dict[str, Any]:
    """Flatten nested mappings into slash-separated keys (leaves only)."""
    out: dict[str, Any] = {}
    if not isinstance(mapping, dict):
        return out
    for key, value in mapping.items():
        path = f"{prefix}/{key}" if prefix else str(key)
        if isinstance(value, dict) and value:
            out.update(_flatten(value, path))
        else:
            out[path] = value
    return out


# --- shared deploy helper ---------------------------------------------------

def _deploy_dict(timeout: float = 120.0) -> dict[str, Any]:
    """Run ``/deploy`` and report the result.

    ``/deploy`` returns 0 even for invalid YAML; ``clean`` therefore also
    requires an empty stderr (design doc §5.6).
    """
    with _DEPLOYER_LOCK:
        deployer = paths.weasel_deployer_exe(paths.weasel_root())
        result = _deploy.run_deploy(deployer, timeout=timeout)
    return {
        "ran": result.ran,
        "exit_code": result.exit_code,
        "timed_out": result.timed_out,
        "busy": result.busy,
        "stderr": result.stderr,
        "note": result.note,
        "clean": bool(result.ran)
        and result.exit_code == 0
        and not (result.stderr or "").strip(),
    }


def run_deploy(timeout: float = 120.0) -> dict[str, Any]:
    """Public wrapper: run ``/deploy`` and report the checked result.

    ``clean`` requires the process to have run, exit code ``0`` **and** an
    empty stderr (design doc §5.6: exit 0 does not prove the config was valid).
    """
    return _deploy_dict(timeout=timeout)


# ============================================================================
# 1. Appearance
# ============================================================================

def _resolve_requested(values: dict[str, Any]) -> dict[str, dict[str, Any]]:
    resolved: dict[str, dict[str, Any]] = {}
    for wanted, actual in REQUESTED_STYLE_KEYS.items():
        if actual in values:
            resolved[wanted] = {
                "exists": True,
                "value": values[actual],
                "actual_path": actual,
            }
        else:
            resolved[wanted] = {
                "exists": False,
                "value": None,
                "actual_path": None,
            }
            if wanted != actual:
                resolved[wanted]["hint"] = f"实际键为 {actual}"
    return resolved


def read_weasel_style(
    weasel_root: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Read the **installed** ``weasel.yaml`` and enumerate its real style keys.

    Returns a flattened ``style`` mapping (``style/layout/corner_radius`` etc.),
    the sorted list of every real key, the requested-key resolution and the
    available ``preset_color_schemes`` names.  Never raises on a missing file.
    """
    path = _weasel_yaml_path(weasel_root)
    document = _load_yaml(path) if path is not None else None
    style = document.get("style") if isinstance(document, dict) else None
    flat = _flatten(style, "style")
    presets = document.get("preset_color_schemes") if isinstance(document, dict) else None
    return {
        "weasel_root": str(_weasel_root(weasel_root)) if _weasel_root(weasel_root) else None,
        "weasel_yaml": str(path) if path is not None else None,
        "exists": isinstance(document, dict),
        "style": flat,
        "available_keys": sorted(flat),
        "requested": _resolve_requested(flat),
        "preset_color_schemes": sorted(str(k) for k in presets)
        if isinstance(presets, dict)
        else [],
    }


def available_color_schemes(
    weasel_root: str | os.PathLike[str] | None = None,
    user_dir: str | os.PathLike[str] | None = None,
) -> list[str]:
    """Colour-scheme names derived from the install's ``preset_color_schemes``.

    The currently selected scheme is appended if the install no longer ships it,
    so the UI can always show the effective value.
    """
    path = _weasel_yaml_path(weasel_root)
    document = _load_yaml(path) if path is not None else None
    names: list[str] = []
    if isinstance(document, dict):
        presets = document.get("preset_color_schemes")
        if isinstance(presets, dict):
            names = sorted(str(k) for k in presets)
    patch = weasel_custom_patch(user_dir)
    effective = patch.get("style/color_scheme")
    if effective and str(effective) not in names:
        names.append(str(effective))
    return names


def weasel_custom_patch(
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Flattened ``patch:`` mapping of ``weasel.custom.yaml`` (read-only)."""
    path = _custom_weasel_path(user_dir)
    document = _load_yaml(path)
    patch = document.get("patch") if isinstance(document, dict) else None
    return _flatten(patch, "")


def current_style(
    user_dir: str | os.PathLike[str] | None = None,
    weasel_root: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Effective style = installed defaults overlaid by ``weasel.custom.yaml``."""
    base = read_weasel_style(weasel_root)
    defaults: dict[str, Any] = dict(base["style"])
    patch = weasel_custom_patch(user_dir)
    values = dict(defaults)
    values.update(patch)
    custom = _custom_weasel_path(user_dir)
    return {
        "weasel_yaml": base["weasel_yaml"],
        "custom_path": str(custom),
        "custom_exists": custom.is_file(),
        "defaults": defaults,
        "patch": patch,
        "values": values,
        "requested": _resolve_requested(values),
    }


# -- weasel.custom.yaml editing ----------------------------------------------
#
# ``weasel.custom.yaml`` is a plain Rime ``patch:`` file.  A patch key may be
# written either flat (``"style/font_point": 15``) or nested::
#
#     patch:
#       style:
#         font_point: 15
#
# librime treats the two spellings identically (``/`` is a path separator), so
# both reads and writes must resolve the *flattened* path.  A ruamel
# round-trip document is used (like :mod:`schema_patch`) so comments and the
# unrelated structure survive.  This replaces the old flat-only line editor,
# which appended a duplicate flat key for a nested file and silently did
# nothing when asked to remove a nested key (S6).


def _find_leaf(mapping: dict, parts: list[str]):
    """Return ``(parent_mapping, leaf_key)`` for slash-path ``parts`` or ``None``."""
    joined = "/".join(parts)
    if joined in mapping and not isinstance(mapping[joined], dict):
        return mapping, joined
    if len(parts) == 1:
        return None
    child = mapping.get(parts[0])
    if isinstance(child, dict):
        return _find_leaf(child, parts[1:])
    return None


def _prune_empty_maps(mapping: dict) -> None:
    """Recursively drop nested mappings that became empty (keeps the root)."""
    for key in list(mapping.keys()):
        value = mapping[key]
        if isinstance(value, dict):
            _prune_empty_maps(value)
            if not value:
                del mapping[key]


def _edit_weasel_patch(text: str, changes: dict[str, Any]) -> str:
    """Return ``text`` with ``changes`` merged into the ``patch:`` mapping.

    ``changes`` keys are slash paths (``style/font_point``); they are resolved
    against the flattened patch, so the flat and nested spellings are
    equivalent.  A ``None`` value removes the key (and prunes a parent mapping
    that becomes empty).  A ruamel round-trip document preserves comments and
    the rest of the file.
    """
    yaml = _require_yaml()()
    yaml.preserve_quotes = True
    yaml.allow_unicode = True
    yaml.default_flow_style = False
    yaml.indent(mapping=2, sequence=4, offset=2)
    try:
        document = yaml.load(text) if text.strip() else None
    except Exception as exc:  # noqa: BLE001 - malformed user file
        raise RimeSettingsError(f"cannot parse weasel.custom.yaml: {exc}") from exc
    map_class = _require_map()
    if document is None:
        document = map_class()
    if not isinstance(document, dict):
        raise RimeSettingsError("weasel.custom.yaml is not a YAML mapping")
    patch = document.get("patch")
    if not isinstance(patch, dict):
        patch = map_class()
        document["patch"] = patch

    for key, value in changes.items():
        parts = [part for part in str(key).split("/") if part]
        if not parts:
            continue
        found = _find_leaf(patch, parts)
        if value is None:
            if found is not None:
                parent, leaf = found
                del parent[leaf]
                _prune_empty_maps(patch)
            continue
        if found is not None:
            parent, leaf = found
            parent[leaf] = value
            continue
        # Create the nested mapping chain for a key that does not exist yet.
        target = patch
        for part in parts[:-1]:
            child = target.get(part)
            if not isinstance(child, dict):
                child = map_class()
                target[part] = child
            target = child
        target[parts[-1]] = value

    buffer = StringIO()
    yaml.dump(document, buffer)
    return buffer.getvalue()


def _normalize_style_key(key: str) -> str:
    normalized = str(key).strip()
    if not normalized.startswith("style/"):
        normalized = "style/" + normalized
    return REQUESTED_STYLE_KEYS.get(normalized, normalized)


def _coerce_style_value(value: Any) -> Any:
    if value is None or isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value
    text = str(value).strip()
    lowered = text.lower()
    if lowered in ("true", "yes", "on"):
        return True
    if lowered in ("false", "no", "off"):
        return False
    if re.fullmatch(r"-?\d+", text):
        return int(text)
    if re.fullmatch(r"-?\d+\.\d+", text):
        return float(text)
    return text


def apply_style(
    patch: dict[str, Any],
    *,
    deploy: bool = True,
    user_dir: str | os.PathLike[str] | None = None,
    weasel_root: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Merge ``patch`` into ``weasel.custom.yaml`` and (optionally) redeploy.

    Keys may be slash paths (``style/font_point``), bare names
    (``font_point``) or the design-doc alias ``style/corner_radius``.  A value
    of ``None`` removes the key (used to restore the original state).
    """
    changes: dict[str, Any] = {}
    for key, value in patch.items():
        changes[_normalize_style_key(key)] = _coerce_style_value(value)

    path = _custom_weasel_path(user_dir)
    original = path.read_text(encoding="utf-8-sig") if path.is_file() else ""
    updated = _edit_weasel_patch(original, changes)
    changed = updated != original
    backup: Path | None = None
    if changed:
        backup = yaml_io.backup_file(path)
        yaml_io.atomic_write_text(path, updated)

    result: dict[str, Any] = {
        "action": "apply_style",
        "custom_path": str(path),
        "changes": {k: v for k, v in changes.items()},
        "changed": changed,
        "backup_path": str(backup) if backup else None,
        "custom_exists": path.is_file(),
        "applied": {},
        "deploy": None,
        "clean": None,
    }
    if changed:
        result["applied"] = current_style(user_dir, weasel_root)["values"]

    if deploy and changed:
        result["deploy"] = _deploy_dict()
        result["clean"] = bool(result["deploy"]["clean"])
        # Re-read the state after deploying (exit code 0 is not proof).
        result["effective"] = current_style(user_dir, weasel_root)["values"]
    return result


# ============================================================================
# 2. Switches
# ============================================================================

def _schema_switch_defs(
    schema_id: str, user_dir: str | os.PathLike[str] | None = None
) -> dict[str, dict[str, Any]]:
    """Switch name -> ``{default, states, kind}`` from the compiled schema."""
    document = _load_yaml(_compiled_schema_path(schema_id, user_dir))
    defs: dict[str, dict[str, Any]] = {}
    if not isinstance(document, dict):
        return defs
    switches = document.get("switches")
    if not isinstance(switches, list):
        return defs

    for item in switches:
        if not isinstance(item, dict):
            continue
        name = item.get("name")
        reset = item.get("reset")
        states = item.get("states") or []
        if isinstance(name, str) and name.startswith("language_input_"):
            default = bool(reset) if isinstance(reset, (bool, int)) else None
            defs[name] = {"default": default, "states": states, "kind": "bool"}
            continue
        options = item.get("options")
        if isinstance(options, (list, tuple)) and any(
            isinstance(option, str) and option.startswith("language_input_")
            for option in options
        ):
            for index, option in enumerate(options):
                if not isinstance(option, str):
                    continue
                default = None
                if isinstance(reset, int) and 0 <= reset < len(options):
                    default = index == reset
                defs[option] = {
                    "default": default,
                    "states": states,
                    "kind": "language",
                    "group": [str(o) for o in options],
                }
    return defs


def _combined_switch_defs(
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, dict[str, Any]]:
    combined: dict[str, dict[str, Any]] = {}
    for schema_id in LANGUAGE_SCHEMAS:
        for name, definition in _schema_switch_defs(schema_id, user_dir).items():
            combined.setdefault(name, definition)
    return combined


def language_input_switches(
    user_dir: str | os.PathLike[str] | None = None,
) -> list[dict[str, Any]]:
    """Describe every Language Input switch with label, value and schema default.

    ``default`` is the explicit ``reset`` value from the compiled schema (the
    UI renders it as 「默认」); it is ``None`` once the resets have been
    neutralized, in which case the saved value is authoritative.
    """
    defs = _combined_switch_defs(user_dir)
    saved = yaml_io.read_user_yaml_options(_user_yaml_path(user_dir))
    rows: list[dict[str, Any]] = []
    for name in SWITCH_ORDER:
        definition = defs.get(name, {})
        default = definition.get("default")
        saved_value = saved.get(name)
        if saved_value is not None:
            value = saved_value
        elif default is not None:
            value = default
        else:
            value = False
        if default is None:
            default_label = "默认：未知（未编译）"
        else:
            default_label = "默认：" + ("开" if default else "关")
        rows.append(
            {
                "name": name,
                "label": SWITCH_LABELS.get(name, name),
                "group": "language" if name in LANGUAGE_GROUP else None,
                "kind": definition.get("kind", "bool"),
                "states": definition.get("states", []),
                "value": bool(value),
                "saved": saved_value,
                "default": default,
                "default_label": default_label,
            }
        )
    return rows


def read_switches(
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, bool]:
    """Saved ``var/option/*`` booleans from ``user.yaml`` (read-only)."""
    return yaml_io.read_user_yaml_options(_user_yaml_path(user_dir))


def set_switches(
    changes: dict[str, bool],
    *,
    deploy: bool = True,
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Atomically set one or more ``var/option/*`` switches, then redeploy.

    The three language options are mutually exclusive: turning any one on
    clears the other two.

    The ``user.yaml`` write is a full stop → wait → atomic-write → restart
    transaction (:func:`server.server_stopped`), because the running server
    holds ``user.yaml`` with ``auto_save`` and rewrites the whole file.  A
    no-op request (all saved values already match) does not touch the server.
    """
    path = _user_yaml_path(user_dir)
    normalized: dict[str, bool] = {}
    for name, value in changes.items():
        if name not in SWITCH_ORDER:
            raise RimeSettingsError(f"unknown switch: {name}")
        normalized[name] = bool(value)

    if any(normalized.get(name) for name in LANGUAGE_GROUP):
        for name in LANGUAGE_GROUP:
            normalized.setdefault(name, False)

    # Only the options whose *saved* value actually differs need a write (this
    # also avoids taking the stop/start transaction for a no-op).
    saved = yaml_io.read_user_yaml_options(path)
    pending = {
        name: value
        for name, value in normalized.items()
        if saved.get(name) != value
    }

    result: dict[str, Any] = {
        "action": "set_switches",
        "requested": normalized,
        "changed": [],
        "user_yaml": str(path),
        "options_after": read_switches(user_dir),
        "server": None,
        "deploy": None,
        "clean": None,
    }
    if not pending:
        return result

    # B2: WeaselServer holds user.yaml with auto_save and rewrites the whole
    # file, so the write must happen with the server stopped (design §5.6).
    # ``server_stopped`` holds the exclusive mutex across the transaction and
    # restarts the server with its previous environment afterwards.
    with _server.server_stopped() as tx:
        changed_keys: list[str] = []
        for name, value in pending.items():
            if yaml_io.set_user_yaml_option(path, name, value):
                changed_keys.append(name)
        result["changed"] = changed_keys

    # ``server_stopped`` restarts the server on exit, so read its final state
    # *after* the ``with`` block (the yielded dict is mutated by the restart).
    result["server"] = {
        "was_running": tx["was_running"],
        "stopped": tx["stopped"],
        "model_host_exited": tx["model_host_exited"],
        "restarted": tx["started"],
        "pids": tx["pids"],
        "restart_error": tx["start_error"],
    }

    result["options_after"] = read_switches(user_dir)
    if deploy and result["changed"]:
        result["deploy"] = _deploy_dict()
        result["clean"] = bool(result["deploy"]["clean"])
        result["options_after"] = read_switches(user_dir)
    return result


def set_switch(
    name: str,
    on: bool,
    *,
    deploy: bool = True,
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Set a single switch; the language options behave as a radio group."""
    return set_switches({name: on}, deploy=deploy, user_dir=user_dir)


# -- hotkeys (read-only) -----------------------------------------------------

_SWITCHER_ACTIONS = {
    "control+grave": "切换输入方案（呼出方案选单）",
    "control+shift+grave": "切换输入方案（呼出方案选单）",
    "f4": "打开选项菜单（方案选单）",
}

_KEY_NAMES = {
    "control": "Ctrl",
    "shift": "Shift",
    "alt": "Alt",
    "grave": "`",
    "minus": "-",
    "equal": "=",
    "comma": ",",
    "period": ".",
    "bracketleft": "[",
    "bracketright": "]",
    "space": "空格",
    "tab": "Tab",
    "iso_left_tab": "Shift+Tab(左)",
    "exclam": "!",
    "at": "@",
    "numbersign": "#",
    "dollar": "$",
    "percent": "%",
}

_SEND_ACTIONS = {
    "Up": "候选/光标上移",
    "Down": "候选/光标下移",
    "Left": "光标左移",
    "Right": "光标右移",
    "Home": "移至行首",
    "End": "移至行尾",
    "Delete": "向后删除",
    "Shift+Delete": "向前删除",
    "BackSpace": "退格",
    "Escape": "取消 / 关闭候选",
    "Page_Up": "上一页候选",
    "Page_Down": "下一页候选",
}

_TOGGLE_ACTIONS = {
    "ascii_mode": "中英文切换",
    "full_shape": "全角 / 半角切换",
    "simplification": "简繁切换",
    "extended_charset": "扩展字符集开关",
}


def _humanize_keys(accept: str) -> str:
    if not accept:
        return ""
    parts = [_KEY_NAMES.get(part.strip().lower(), part.strip()) for part in accept.split("+")]
    return "+".join(parts)


def _binding_effect(binding: dict[str, Any]) -> str:
    if "toggle" in binding:
        target = str(binding["toggle"])
        return _TOGGLE_ACTIONS.get(target, f"切换 {target}")
    if "select" in binding:
        target = str(binding["select"])
        return "切换到下一方案" if target == ".next" else f"选择 {target}"
    if "send" in binding:
        target = str(binding["send"])
        return _SEND_ACTIONS.get(target, f"发送 {target}")
    return "（未识别的动作）"


def _raw_binding(binding: dict[str, Any]) -> str:
    return ", ".join(f"{key}={value}" for key, value in binding.items())


def hotkeys(
    user_dir: str | os.PathLike[str] | None = None,
    weasel_root: str | os.PathLike[str] | None = None,
) -> list[dict[str, Any]]:
    """Read-only, human-readable view of the configured key bindings.

    Prefers the compiled ``<userdir>\\build\\default.yaml`` (the merged result);
    falls back to the installed ``default.yaml``.  Nothing is invented: each row
    carries the raw configured value.
    """
    compiled = _coerce_user_dir(user_dir) / "build" / "default.yaml"
    source: Path | None = compiled if compiled.is_file() else None
    if source is None:
        root = _weasel_root(weasel_root)
        candidate = Path(root) / "data" / "default.yaml" if root else None
        source = candidate if candidate is not None and candidate.is_file() else None
    document = _load_yaml(source) if source is not None else None
    if not isinstance(document, dict):
        return []

    rows: list[dict[str, Any]] = []
    switcher = document.get("switcher")
    if isinstance(switcher, dict):
        for raw in switcher.get("hotkeys") or []:
            text = str(raw)
            rows.append(
                {
                    "group": "方案与选项",
                    "keys": _humanize_keys(text),
                    "action": _SWITCHER_ACTIONS.get(text.lower(), "方案选单热键"),
                    "raw": text,
                }
            )

    binder = document.get("key_binder")
    if isinstance(binder, dict):
        for binding in binder.get("bindings") or []:
            if not isinstance(binding, dict):
                continue
            rows.append(
                {
                    "group": "按键绑定",
                    "keys": _humanize_keys(str(binding.get("accept", ""))),
                    "action": _binding_effect(binding),
                    "raw": _raw_binding(binding),
                }
            )
    return rows


# ============================================================================
# 3. Memory / dictionary
# ============================================================================

def _dir_size(path: Path) -> int:
    total = 0
    if not path.is_dir():
        return 0
    try:
        for entry in path.rglob("*"):
            try:
                if entry.is_file():
                    total += entry.stat().st_size
            except OSError:
                continue
    except OSError:
        return total
    return total


def _custom_has_enable_override(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        document = _load_yaml(path)
    except RimeSettingsError:
        return False
    patch = document.get("patch") if isinstance(document, dict) else None
    return isinstance(patch, dict) and "translator/enable_user_dict" in patch


def learning_state(
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """User-dictionary presence/size + effective ``translator/enable_user_dict``.

    The effective value is read from the compiled schema; when the key is absent
    librime's default is ``true`` (so an absent key means learning is enabled).
    """
    resolved = _coerce_user_dir(user_dir)
    userdb = _userdb_path(user_dir)
    present = userdb.is_dir()
    schemas: dict[str, dict[str, Any]] = {}
    enabled_flags: list[bool] = []
    for schema_id in LANGUAGE_SCHEMAS:
        document = _load_yaml(_compiled_schema_path(schema_id, user_dir))
        translator = document.get("translator") if isinstance(document, dict) else None
        if isinstance(translator, dict) and "enable_user_dict" in translator:
            explicit = True
            value = bool(translator.get("enable_user_dict"))
        else:
            # Rime's built-in default is true; an absent key means enabled.
            explicit = False
            value = True
        custom = _custom_schema_path(schema_id, user_dir)
        schemas[schema_id] = {
            "enable_user_dict": value,
            "explicit": explicit,
            "custom_path": str(custom),
            "custom_exists": custom.is_file(),
            "custom_has_override": _custom_has_enable_override(custom),
        }
        enabled_flags.append(value)
    return {
        "user_dir": str(resolved),
        "userdb_path": str(userdb),
        "userdb_present": present,
        "userdb_size": _dir_size(userdb) if present else 0,
        "schemas": schemas,
        "enabled": all(enabled_flags) if enabled_flags else True,
    }


# -- app-owned <schema>.custom.yaml patching ---------------------------------

def _load_rt(path: Path):
    yaml = _require_yaml()
    try:
        document = yaml().load(path.read_text(encoding="utf-8-sig"))
    except Exception as exc:  # noqa: BLE001 - malformed user file
        raise RimeSettingsError(f"cannot parse existing {path}: {exc}") from exc
    if document is None:
        document = _require_map()()
    if not isinstance(document, dict):
        raise RimeSettingsError(f"{path} is not a YAML mapping")
    return document


def _dump_rt(path: Path, document) -> None:
    yaml = _require_yaml()()
    yaml.default_flow_style = False
    yaml.allow_unicode = True
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)
    from io import StringIO

    buffer = StringIO()
    yaml.dump(document, buffer)
    yaml_io.atomic_write_text(path, buffer.getvalue())


def _custom_meaningful(document) -> bool:
    for key, value in document.items():
        if key == "patch":
            if value:
                return True
            continue
        return True
    return False


def _write_custom_patch_key(path: Path, key: str, value: Any) -> bool:
    if path.is_file():
        document = _load_rt(path)
    else:
        map_class = _require_map()
        document = map_class()
        document["patch"] = map_class()
        setter = getattr(document, "yaml_set_start_comment", None)
        if callable(setter):
            setter(_HEADER_COMMENT)
    patch = document.get("patch")
    if not isinstance(patch, dict):
        patch = _require_map()()
        document["patch"] = patch
    if patch.get(key, _MISSING) == value:
        return False
    yaml_io.backup_file(path)
    patch[key] = value
    _dump_rt(path, document)
    return True


def _remove_custom_patch_key(path: Path, key: str) -> tuple[bool, bool]:
    """Remove ``key`` from the patch; delete the file if nothing remains.

    Returns ``(removed, deleted)``.
    """
    if not path.is_file():
        return False, False
    document = _load_rt(path)
    patch = document.get("patch")
    if not isinstance(patch, dict) or key not in patch:
        return False, False
    del patch[key]
    yaml_io.backup_file(path)
    if _custom_meaningful(document):
        _dump_rt(path, document)
        return True, False
    try:
        path.unlink()
    except OSError as exc:  # pragma: no cover - defensive
        raise RimeSettingsError(f"cannot remove {path}: {exc}") from exc
    return True, True


def set_learning(
    on: bool,
    *,
    deploy: bool = True,
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Toggle ``translator/enable_user_dict`` for both Language Input schemas.

    ``off`` writes ``enable_user_dict: false`` (which also stops *using*
    already-learned words, design doc §8).  ``on`` removes our override so the
    built-in default (true) applies again -- this restores the original files
    (and deletes a custom file that we created and is now empty).
    """
    schemas: dict[str, dict[str, Any]] = {}
    for schema_id in LANGUAGE_SCHEMAS:
        custom = _custom_schema_path(schema_id, user_dir)
        if on:
            removed, deleted = _remove_custom_patch_key(custom, "translator/enable_user_dict")
            schemas[schema_id] = {
                "action": "enable",
                "removed_override": removed,
                "custom_deleted": deleted,
                "custom_path": str(custom),
                "custom_exists": custom.is_file(),
            }
        else:
            written = _write_custom_patch_key(custom, "translator/enable_user_dict", False)
            schemas[schema_id] = {
                "action": "disable",
                "written": written,
                "custom_path": str(custom),
                "custom_exists": custom.is_file(),
            }

    result: dict[str, Any] = {
        "action": "set_learning",
        "on": bool(on),
        "schemas": schemas,
        "deploy": None,
        "clean": None,
    }
    if deploy:
        result["deploy"] = _deploy_dict()
        result["clean"] = bool(result["deploy"]["clean"])
    result["state"] = learning_state(user_dir)
    return result


def sync_user_data(
    *,
    timeout: float = 180.0,
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Run ``WeaselDeployer.exe /sync`` (serialized, bounded by ``timeout``)."""
    with _DEPLOYER_LOCK:
        deployer = paths.weasel_deployer_exe(paths.weasel_root())
        result: dict[str, Any] = {
            "action": "sync_user_data",
            "deployer": str(deployer) if deployer else None,
            "ran": False,
            "exit_code": None,
            "timed_out": False,
            "busy": False,
            "stdout": "",
            "stderr": "",
            "note": "",
            "clean": False,
        }
        if not deployer or not Path(deployer).is_file():
            result["note"] = "WeaselDeployer.exe could not be resolved"
            return result

        try:
            busy = _deploy.is_deployer_running()
        except Exception:  # pragma: no cover - defensive
            busy = False
        if busy:
            result["busy"] = True
            result["note"] = "另一个部署器正在运行；未启动同步。"
            return result

        try:
            completed = subprocess.run(
                [str(deployer), "/sync"],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
                cwd=str(Path(deployer).parent),
                **winproc.no_window_kwargs(),
            )
        except subprocess.TimeoutExpired as exc:
            result["ran"] = True
            result["timed_out"] = True
            result["stdout"] = (exc.stdout or "") if isinstance(exc.stdout, str) else ""
            result["stderr"] = (exc.stderr or "") if isinstance(exc.stderr, str) else ""
            result["note"] = f"/sync timed out after {timeout:g}s"
            return result
        except OSError as exc:
            result["note"] = f"failed to launch /sync: {exc}"
            return result

        result["ran"] = True
        result["exit_code"] = completed.returncode
        result["stdout"] = completed.stdout or ""
        result["stderr"] = completed.stderr or ""
        result["busy"] = completed.returncode == 1
        result["clean"] = completed.returncode == 0 and not result["stderr"].strip()
        if result["busy"]:
            result["note"] = "exit code 1: another deployer is running (busy)"
        elif result["clean"]:
            result["note"] = "用户数据已同步（退出码 0，stderr 为空）。"
        else:
            result["note"] = (
                f"/sync exited with code {completed.returncode}; stderr: "
                f"{result['stderr'].strip() or '（空）'}"
            )
        return result


_DICT_MANAGER_NOTE = (
    "将打开 WeaselDeployer 的「词典管理」窗口（模态对话框）。"
    "该窗口独立运行，本设置应用会立即返回，可继续操作；关闭对话框不会影响设置。"
)


def dict_manager_note() -> str:
    """The UI note explaining that ``/dict`` opens a modal dialog."""
    return _DICT_MANAGER_NOTE


def open_dict_manager(
    *,
    user_dir: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Launch ``WeaselDeployer.exe /dict`` detached (non-blocking).

    The dialog is modal to the deployer process, not to this app, and the call
    returns immediately.
    """
    deployer = paths.weasel_deployer_exe(paths.weasel_root())
    result: dict[str, Any] = {
        "action": "open_dict_manager",
        "deployer": str(deployer) if deployer else None,
        "launched": False,
        "pid": None,
        "note": dict_manager_note(),
    }
    if not deployer or not Path(deployer).is_file():
        result["note"] = "找不到 WeaselDeployer.exe，无法打开词典管理。"
        return result
    try:
        process = subprocess.Popen(
            [str(deployer), "/dict"],
            cwd=str(Path(deployer).parent),
            close_fds=True,
            **winproc.no_window_kwargs(detached=True),
        )
    except OSError as exc:
        result["note"] = f"无法启动词典管理：{exc}"
        return result
    result["launched"] = True
    result["pid"] = process.pid
    return result
