"""Neutralize the explicit ``reset:`` values on Language Input switches.

Background (design doc §5.5 / R19 / V13): ``engine.cc`` calls
``RestoreSavedOptions()`` and then applies each schema switch's explicit
``reset:`` value at session creation, so a saved ``var/option/*`` choice for
AI / model / language / gloss / speech is immediately clobbered.  Both
Language Input schemas ship those ``reset`` values.

The M0 probe verified the fix: writing ``patch: {"switches/@N/reset": null}``
into ``<schema>.custom.yaml`` makes librime emit a null ConfigItem for that
key; ``ConfigMap::EmitYaml`` then omits it and ``rime::reset_value()`` returns
``-1`` so no reset is applied.

Indices are **derived from the compiled schema** (not hardcoded) so this keeps
working if the switch order changes.  All writes follow §5.6: backup, then an
atomic UTF-8 (no BOM) / LF write.
"""

from __future__ import annotations

import sys
from io import StringIO
from pathlib import Path

try:
    from ruamel.yaml import YAML as _YAML
    from ruamel.yaml.comments import CommentedMap as _CommentedMap

    HAS_RUAMEL = True
except Exception:  # pragma: no cover - dependency missing
    _YAML = None  # type: ignore
    _CommentedMap = None  # type: ignore
    HAS_RUAMEL = False


def _require_ruamel() -> None:
    if not HAS_RUAMEL:  # pragma: no cover - dependency missing
        raise SchemaPatchError(
            "ruamel.yaml is required for schema patching "
            "(install the 'ruamel.yaml' dependency)"
        )


def _new_yaml(**kwargs):
    _require_ruamel()
    return _YAML(**kwargs)  # type: ignore[misc]


def _new_map():
    _require_ruamel()
    return _CommentedMap()  # type: ignore[misc]

from . import paths
from .yaml_io import atomic_write_text, backup_file

__all__ = [
    "SchemaPatchError",
    "compiled_schema_path",
    "custom_schema_path",
    "compiled_reset_state",
    "language_input_switch_indices",
    "neutralize_resets",
    "revert_resets",
]

_SWITCH_PREFIX = "language_input_"
_MISSING = object()

_HEADER_COMMENT = (
    "Generated by Language Input settings: neutralize the explicit `reset:`\n"
    "values on the Language Input switches so saved var/option/* values are\n"
    "not overridden when a session is created (design doc §5.5 / R19).\n"
    "Setting the key to YAML null makes librime omit it after patching.\n"
)


class SchemaPatchError(RuntimeError):
    """The schema patch could not be applied safely."""


def _user_dir(user_dir: Path | None) -> Path:
    return Path(user_dir) if user_dir is not None else paths.rime_user_dir()


def compiled_schema_path(schema_id: str, user_dir: Path | None = None) -> Path:
    """``<userdir>\\build\\<schema_id>.schema.yaml``."""
    return _user_dir(user_dir) / "build" / f"{schema_id}.schema.yaml"


def custom_schema_path(schema_id: str, user_dir: Path | None = None) -> Path:
    """``<userdir>\\<schema_id>.custom.yaml`` (the patch attachment point)."""
    return _user_dir(user_dir) / f"{schema_id}.custom.yaml"


# --- compiled-schema parsing ------------------------------------------------

def _read_switches(schema_id: str, user_dir: Path | None) -> list:
    _require_ruamel()
    path = compiled_schema_path(schema_id, user_dir)
    if not path.is_file():
        raise SchemaPatchError(
            f"compiled schema not found: {path} (run a deploy first)"
        )
    try:
        document = _new_yaml(typ="safe").load(path.read_text(encoding="utf-8-sig"))
    except Exception as exc:  # noqa: BLE001 - malformed compiled schema
        raise SchemaPatchError(f"cannot parse {path}: {exc}") from exc
    if not isinstance(document, dict):
        raise SchemaPatchError(f"{path} is not a YAML mapping")
    switches = document.get("switches")
    if not isinstance(switches, list):
        raise SchemaPatchError(f"{path} has no 'switches' sequence")
    return switches


def _is_language_input_switch(item: object) -> bool:
    if not isinstance(item, dict):
        return False
    name = item.get("name")
    if isinstance(name, str) and name.startswith(_SWITCH_PREFIX):
        return True
    options = item.get("options")
    if isinstance(options, (list, tuple)):
        return any(
            isinstance(option, str) and option.startswith(_SWITCH_PREFIX)
            for option in options
        )
    return False


def _switch_key(item: dict, index: int) -> str:
    name = item.get("name")
    if isinstance(name, str) and name:
        return name
    options = item.get("options")
    if isinstance(options, (list, tuple)) and options:
        return "|".join(str(option) for option in options)
    return f"@switch{index}"


def language_input_switch_indices(
    schema_id: str, user_dir: Path | None = None
) -> list[int]:
    """Indices of Language Input switches in the compiled ``switches`` list."""
    switches = _read_switches(schema_id, user_dir)
    return [
        index
        for index, item in enumerate(switches)
        if _is_language_input_switch(item)
    ]


def compiled_reset_state(
    schema_id: str, user_dir: Path | None = None
) -> dict[str, bool]:
    """``{switch: still_has_reset}`` for every Language Input switch.

    Read back from the **compiled** schema, so it reflects the result of the
    most recent deploy.  The unnamed language group is keyed by its options
    joined with ``|``.
    """
    switches = _read_switches(schema_id, user_dir)
    state: dict[str, bool] = {}
    for index, item in enumerate(switches):
        if not _is_language_input_switch(item):
            continue
        state[_switch_key(item, index)] = "reset" in item
    return state


# --- custom-file load / dump ------------------------------------------------

def _dump_custom(path: Path, document) -> None:
    yaml = _new_yaml()
    yaml.default_flow_style = False
    yaml.allow_unicode = True
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)
    buffer = StringIO()
    yaml.dump(document, buffer)
    atomic_write_text(path, buffer.getvalue())


def _load_custom(path: Path) -> tuple[object, bool]:
    """Return ``(document, existed)``; never clobbers an unparseable file."""
    if not path.is_file():
        document = _new_map()
        document["patch"] = _new_map()
        setter = getattr(document, "yaml_set_start_comment", None)
        if callable(setter):
            setter(_HEADER_COMMENT)
        return document, False
    try:
        document = _new_yaml().load(path.read_text(encoding="utf-8-sig"))
    except Exception as exc:  # noqa: BLE001 - malformed user file
        raise SchemaPatchError(f"cannot parse existing {path}: {exc}") from exc
    if document is None:
        document = _new_map()
    if not isinstance(document, dict):
        raise SchemaPatchError(f"{path} is not a YAML mapping")
    return document, True


def _existing_patch(document):
    """Return the existing ``patch`` mapping, or ``None`` when absent."""
    patch = document.get("patch")
    return patch if isinstance(patch, dict) else None


def _ensure_patch(document):
    """Return the ``patch`` mapping, creating it when absent."""
    patch = document.get("patch")
    if not isinstance(patch, dict):
        patch = _new_map()
        document["patch"] = patch
    return patch


def _has_meaningful_content(document) -> bool:
    for key, value in document.items():
        if key == "patch":
            if value:  # non-empty mapping
                return True
            continue
        return True
    return False


# --- public operations ------------------------------------------------------

def neutralize_resets(schema_id: str, user_dir: Path | None = None) -> Path:
    """Write/merge ``<schema>.custom.yaml`` to null the Language Input resets.

    Merges into any existing custom file without touching other keys and is
    idempotent.  Only the switch entries that currently carry ``reset:`` are
    patched.  Deployment is a separate step (the caller runs ``/deploy``).
    """
    switches = _read_switches(schema_id, user_dir)
    indices = [
        index
        for index, item in enumerate(switches)
        if _is_language_input_switch(item) and "reset" in item
    ]
    custom = custom_schema_path(schema_id, user_dir)
    if not indices:
        # Nothing to neutralize (already applied + deployed, or no resets).
        return custom

    document, existed = _load_custom(custom)
    patch = _ensure_patch(document)
    changed = False
    for index in indices:
        key = f"switches/@{index}/reset"
        if patch.get(key, _MISSING) is not None:
            patch[key] = None
            changed = True
    if changed or not existed:
        backup_file(custom)
        _dump_custom(custom, document)
    return custom


def revert_resets(schema_id: str, user_dir: Path | None = None) -> Path | None:
    """Remove our ``switches/@N/reset`` patch keys from ``<schema>.custom.yaml``.

    Indices come from the compiled schema's **switch positions** (stable even
    after a deploy removed the resets).  If the custom file has no other
    content afterwards it is deleted.  Returns the custom path, or ``None``
    when the file no longer exists / was deleted.
    """
    custom = custom_schema_path(schema_id, user_dir)
    if not custom.is_file():
        return None
    # Indices are positional, so this still works after the resets are gone
    # from the compiled schema.
    indices = language_input_switch_indices(schema_id, user_dir)

    document, _existed = _load_custom(custom)
    patch = _existing_patch(document)
    removed = False
    if patch is not None:
        for index in indices:
            key = f"switches/@{index}/reset"
            if key in patch:
                del patch[key]
                removed = True

    if not _has_meaningful_content(document):
        try:
            custom.unlink()
        except OSError as exc:  # pragma: no cover - defensive
            raise SchemaPatchError(f"cannot remove {custom}: {exc}") from exc
        return None

    if removed:
        backup_file(custom)
        _dump_custom(custom, document)
    return custom
